CHIP_CONFIG = {
    "chip_name": "bes1310",
    "main_die": "BES1310",
    "main_die_version": "",
    "main_die_i2c_width": "",
    "main_die_i2c_addr": "",
    "main_die_pmu": "",
    "main_die_pmu_version": "",
    'main_die_pmu_i2c_width': '10',
    'main_die_pmu_i2c_addr': '0x27',
    "has_pmu": "",
    "pmu": "PMU1310",
    "pmu_version": "",
    "pmu_i2c_width": "",
    "pmu_i2c_addr": "",
    "flash1": "",
    "flash2": "",
    "flash3": "",
    "psram1": "",
    "psram2": "",
    "apsram1": "",
    "apsram2": "",
    "power_distribution": {},
}
