CHIP_CONFIG = {
    'chip_name': 'bes1307ph',
    'main_die': 'BES1307PH',
    'main_die_version': '',
    'main_die_i2c_width': '',
    'main_die_i2c_addr': '',
    'main_die_pmu': '',
    'main_die_pmu_version': '',
    'main_die_pmu_i2c_width': '',
    'main_die_pmu_i2c_addr': '',
    'has_pmu': False,
    'pmu': '',
    'pmu_version': '',
    'pmu_i2c_width': '',
    'pmu_i2c_addr': '',
    'flash1': '',
    'flash2': '',
    'flash3': '',
    'psram1': '',
    'psram2': '',
    'apsram1': '',
    'apsram2': '',
    'power_distribution': {'user_config': ['Voltage_low:', '- WRITE_BITS 0x0132 7 0 0x0F', '- WRITE_BITS 0x0133 7 0 0x0F', '- WRITE 0x0128 0x2108', '- WRITE_BITS 0x0135 15 8 0x0F', '- WRITE_BITS 0x0136 15 8 0x0F']},
}
