CHIP_CONFIG = {
    "chip_name": "bes1607",
    "main_die": "BES1607",
    "main_die_version": "",
    "main_die_i2c_width": "32",
    "main_die_i2c_addr": "0x11",
    "main_die_pmu": "BESC0DE",
    "main_die_pmu_version": "",
    "main_die_pmu_i2c_width": "10",
    "main_die_pmu_i2c_addr": "0x27",
    "has_pmu": "",
    "pmu": "PMU1806P",
    "pmu_version": "",
    "pmu_i2c_width": "10",
    "pmu_i2c_addr": "0x17",
    "flash1": "",
    "flash2": "",
    "flash3": "",
    "psram1": "",
    "psram2": "",
    "apsram1": "",
    "apsram2": "",
    "power_distribution": {},
}
