# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for KK_Lab Main Application

#run cmd
# 带 AI（默认）
#python -m PyInstaller spec/kk_lab.spec --clean --noconfirm

# 不带 AI：临时设环境变量后再打包
#$env:KK_LAB_WITH_AI="0"; python -m PyInstaller spec/kk_lab.spec --clean --noconfirm; Remove-Item Env:KK_LAB_WITH_AI

import os

block_cipher = None

# Project root (spec file is in spec/ subdirectory)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(SPEC)))

a = Analysis(
    [os.path.join(PROJECT_ROOT, 'main.py')],
    pathex=[
        PROJECT_ROOT,
        os.path.join(PROJECT_ROOT, 'lib', 'i2c'),
        os.path.join(PROJECT_ROOT, 'lib', 'download_tools'),
        os.path.join(PROJECT_ROOT, 'chips'),
    ],
    binaries=[],
    datas=[
        (os.path.join(PROJECT_ROOT, 'resources', 'icons'), os.path.join('resources', 'icons')),
        (os.path.join(PROJECT_ROOT, 'resources', 'icons_svg'), os.path.join('resources', 'icons_svg')),
        (os.path.join(PROJECT_ROOT, 'resources', 'pages'), os.path.join('resources', 'pages')),
        (os.path.join(PROJECT_ROOT, 'resources', 'modules'), os.path.join('resources', 'modules')),
        (os.path.join(PROJECT_ROOT, 'resources', 'ai'), os.path.join('resources', 'ai')),
        (os.path.join(PROJECT_ROOT, 'lib', 'i2c'), os.path.join('lib', 'i2c')),
        (os.path.join(PROJECT_ROOT, 'lib', 'download_tools'), os.path.join('lib', 'download_tools')),
        (os.path.join(PROJECT_ROOT, 'chips'), 'chips'),
        (os.path.join(PROJECT_ROOT, 'helps'), 'helps'),
        (
            os.path.join(PROJECT_ROOT, 'ui', 'pages', 'custom_test', 'templates'),
            os.path.join('ui', 'pages', 'custom_test', 'templates'),
        ),
    ],
    hiddenimports=[
        'pyvisa',
        'pyvisa_py',
        'pyvisa_py.tcpip',
        'pyvisa_py.protocols',
        'pyvisa_py.protocols.vxi11',
        'pyvisa_py.protocols.rpc',
        'pyqtgraph',
        'numpy',
        'PySide6',
        'PySide6.QtSvg',
        'serial',
        'serial.tools',
        'serial.tools.list_ports',
        'openpyxl',
        'log_config',
        'debug_config',
        'httpx',
        'core.ai',
        'core.ai.config',
        'core.ai.newapi_client',
        'core.ai.profiles',
        'core.ai.prompt_manager',
        'core.ai.ai_service',
        'core.ai.log_ring',
        'core.ai.response_parser',
        'core.ai.draft_validation',
        'core.ai.providers',
        'core.ai.providers.base',
        'core.ai.providers.page_provider',
        'core.ai.actions',
        'core.ai.actions.registry',
        'core.ai.actions.permission',
        'core.ai.actions.dispatcher',
        'core.ai.actions.audit',
        'core.ai.actions.builder',
        'core.ai.actions.handlers',
        'core.ai.actions.handlers.deps',
        'core.ai.actions.handlers.query',
        'core.ai.actions.handlers.ui',
        'core.ai.actions.handlers.serial',
        'core.ai.actions.handlers.instrument',
        'core.ai.actions.handlers.test',
        'ui.app_top_bar',
        'ui.ai',
        'ui.ai.ai_panel_button',
        'ui.ai.ai_assist_panel',
        'ui.ai.chat_view',
        'ui.ai.config_preview',
        'ui.ai.script_preview',
        'ui.ai.action_confirm_dialog',
        'ui.ai.ai_settings_dialog',
        'ui.ai.panel_state',
        'instruments',
        'instruments.base',
        'instruments.base.instrument_base',
        'instruments.base.visa_instrument',
        'instruments.base.exceptions',
        'instruments.scopes',
        'instruments.scopes.base',
        'instruments.scopes.keysight',
        'instruments.scopes.keysight.dsox4034a',
        'instruments.scopes.keysight.dsox_lib',
        'instruments.scopes.tektronix',
        'instruments.scopes.tektronix.mso64b',
        'instruments.power',
        'instruments.power.keysight',
        'instruments.power.keysight.n6705c',
        'instruments.power.keysight.n6705c_datalog_process',
        'instruments.chambers',
        'instruments.chambers.base',
        'instruments.chambers.mt3065',
        'instruments.chambers.vt6002_chamber',
        'instruments.chambers.wt2040_chamber',
        'instruments.chambers.temperature_stabilizer',
        'instruments.mock',
        'instruments.mock.mock_instruments',
        'instruments.adapters',
        'instruments.factory',
        'core',
        'core.test_manager',
        'core.data_collector',
        'core.controllers',
        'core.controllers.oscilloscope_controller',
        'chips',
        'chips.bes_chip_configs',
        'chips.bes_chip_configs.bes_chip_configs',
        'chips.bes_chip_configs.main_chips',
        'chips.bes_chip_configs.pmu_chips',
        'ui',
        'ui.resource_path',
        'ui.main_window',
        'ui.widgets',
        'ui.widgets.plot_widget',
        'ui.widgets.sidebar_nav_button',
        'ui.widgets.dark_combobox',
        'ui.widgets.scrollbar',
        'ui.widgets.button',
        'ui.widgets.progress_button',
        'ui.widgets.start_sequence',
        'ui.dialogs',
        'ui.styles',
        'ui.modules',
        'ui.modules.execution_logs_module_frame',
        'ui.modules.n6705c_module_frame',
        'ui.modules.oscilloscope_module_frame',
        'ui.modules.chamber_module_frame',
        'ui.modules.serialCom_module.serialCom_module_frame',
        'ui.modules.serialCom_module.serialCom_apple_gpt5p5_style',
        'ui.modules.serialCom_module.serialCom_dark_style',
        'ui.modules.serialCom_module.serial_session',
        'ui.modules.serialCom_module.serial_session_manager',
        'ui.modules.serialCom_module.serial_chart_model',
        'ui.modules.serialCom_module.serial_chart_parser',
        'ui.modules.serialCom_module.serial_chart_controller',
        'ui.modules.serialCom_module.serial_chart_dialog',
        'ui.pages',
        'ui.pages.n6705c_power_analyzer',
        'ui.pages.n6705c_power_analyzer.n6705c_top',
        'ui.pages.n6705c_power_analyzer.n6705c_analyser_ui',
        'ui.pages.n6705c_power_analyzer.n6705c_datalog_ui',
        'ui.pages.oscilloscope',
        'ui.pages.oscilloscope.oscilloscope_base_ui',
        'ui.pages.oscilloscope.mso64b_top',
        'ui.pages.pmu_test',
        'ui.pages.pmu_test.pmu_test_ui',
        'ui.pages.pmu_test.pmu_dcdc_efficiency',
        'ui.pages.pmu_test.pmu_output_voltage',
        'ui.pages.pmu_test.pmu_isGain_ui',
        'ui.pages.pmu_test.pmu_oscp_ui',
        'ui.pages.pmu_test.gpadc_test_ui',
        'ui.pages.pmu_test.clk_test_ui',
        'ui.pages.chamber',
        'ui.pages.chamber.chamber_control_ui',
        'ui.pages.charger_test',
        'ui.pages.charger_test.charger_test_ui',
        'ui.pages.charger_test.config_traverse_test',
        'ui.pages.charger_test.iterm_test',
        'ui.pages.charger_test.regulation_voltage_ui',
        'ui.pages.charger_test.status_register_test',
        'ui.pages.consumption_test',
        'ui.pages.consumption_test.consumption_test',
        'ui.pages.consumption_test.consumption_test_wrapper',
        'ui.pages.consumption_test.high_low_temp_test_ui',
        'ui.pages.consumption_test.consumption_test_workers',
        'ui.pages.consumption_test.consumption_test_workers.common',
        'ui.pages.consumption_test.consumption_test_workers.download_worker',
        'ui.pages.consumption_test.consumption_test_workers.chip_check_worker',
        'ui.pages.consumption_test.consumption_test_workers.consumption_worker',
        'ui.pages.consumption_test.consumption_test_workers.force_worker',
        'ui.pages.consumption_test.consumption_test_workers.auto_test_worker',
        'Bes_I2CIO_Interface',
        'i2c_interface_x64',
        'i2c_demo_x64',
        'efuse_script_caller',
        'lib.i2c.Bes_I2CIO_Interface',
        'lib.i2c.i2c_interface_x64',
        'lib.i2c.i2c_demo_x64',
        'lib.i2c.efuse_script_caller',
        'lib.download_tools.download_script',
    ],
    hookspath=[os.path.join(PROJECT_ROOT, 'hooks')],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pyqtgraph.opengl',
        'OpenGL',
        'importlib_resources',
        'serial.tools.list_ports_osx',
        'numpy.array_api',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='KK_Lab',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(PROJECT_ROOT, 'resources', 'icons', 'kk_lab.ico'),
)
