# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for KK_Lab Main Application

#run cmd
#python -m PyInstaller spec/kk_lab.spec --clean --noconfirm


import os

block_cipher = None

# Project root (spec file is in spec/ subdirectory)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(SPEC)))

a = Analysis(
    [os.path.join(PROJECT_ROOT, 'main.py')],
    pathex=[
        PROJECT_ROOT,
        os.path.join(PROJECT_ROOT, 'lib', 'i2c'),
        os.path.join(PROJECT_ROOT, 'lib', 'download_tools'),
        os.path.join(PROJECT_ROOT, 'chips'),
    ],
    binaries=[],
    datas=[
        (os.path.join(PROJECT_ROOT, 'resources', 'icons'), os.path.join('resources', 'icons')),
        (os.path.join(PROJECT_ROOT, 'lib', 'i2c'), os.path.join('lib', 'i2c')),
        (os.path.join(PROJECT_ROOT, 'lib', 'download_tools'), os.path.join('lib', 'download_tools')),
        (os.path.join(PROJECT_ROOT, 'chips'), 'chips'),
        (os.path.join(PROJECT_ROOT, 'helps'), 'helps'),
    ],
    hiddenimports=[
        'pyvisa',
        'pyvisa_py',
        'pyvisa_py.tcpip',
        'pyvisa_py.protocols',
        'pyvisa_py.protocols.vxi11',
        'pyvisa_py.protocols.rpc',
        'pyqtgraph',
        'numpy',
        'PySide6',
        'PySide6.QtSvg',
        'serial',
        'serial.tools',
        'serial.tools.list_ports',
        'openpyxl',
        'log_config',
        'debug_config',
        'instruments',
        'instruments.base',
        'instruments.base.instrument_base',
        'instruments.base.visa_instrument',
        'instruments.base.exceptions',
        'instruments.scopes',
        'instruments.scopes.base',
        'instruments.scopes.keysight',
        'instruments.scopes.keysight.dsox4034a',
        'instruments.scopes.keysight.dsox_lib',
        'instruments.scopes.tektronix',
        'instruments.scopes.tektronix.mso64b',
        'instruments.power',
        'instruments.power.keysight',
        'instruments.power.keysight.n6705c',
        'instruments.power.keysight.n6705c_datalog_process',
        'instruments.chambers',
        'instruments.chambers.vt6002_chamber',
        'instruments.mock',
        'instruments.mock.mock_instruments',
        'instruments.adapters',
        'instruments.factory',
        'core',
        'core.test_manager',
        'core.data_collector',
        'core.controllers',
        'core.controllers.oscilloscope_controller',
        'chips',
        'chips.bes_chip_configs',
        'chips.bes_chip_configs.bes_chip_configs',
        'chips.bes_chip_configs.main_chips',
        'chips.bes_chip_configs.pmu_chips',
        'ui',
        'ui.main_window',
        'ui.widgets',
        'ui.widgets.plot_widget',
        'ui.widgets.sidebar_nav_button',
        'ui.widgets.dark_combobox',
        'ui.widgets.scrollbar',
        'ui.widgets.button',
        'ui.widgets.progress_button',
        'ui.widgets.start_sequence',
        'ui.dialogs',
        'ui.styles',
        'ui.modules',
        'ui.modules.execution_logs_module_frame',
        'ui.modules.n6705c_module_frame',
        'ui.modules.oscilloscope_module_frame',
        'ui.modules.chamber_module_frame',
        'ui.modules.serialCom_module_frame',
        'ui.pages',
        'ui.pages.n6705c_power_analyzer',
        'ui.pages.n6705c_power_analyzer.n6705c_top',
        'ui.pages.n6705c_power_analyzer.n6705c_analyser_ui',
        'ui.pages.n6705c_power_analyzer.n6705c_datalog_ui',
        'ui.pages.oscilloscope',
        'ui.pages.oscilloscope.oscilloscope_base_ui',
        'ui.pages.oscilloscope.mso64b_top',
        'ui.pages.pmu_test',
        'ui.pages.pmu_test.pmu_test_ui',
        'ui.pages.pmu_test.pmu_dcdc_efficiency',
        'ui.pages.pmu_test.pmu_output_voltage',
        'ui.pages.pmu_test.pmu_isGain_ui',
        'ui.pages.pmu_test.pmu_oscp_ui',
        'ui.pages.pmu_test.gpadc_test_ui',
        'ui.pages.pmu_test.clk_test_ui',
        'ui.pages.chamber',
        'ui.pages.chamber.vt6002_chamber_ui',
        'ui.pages.charger_test',
        'ui.pages.charger_test.charger_test_ui',
        'ui.pages.charger_test.config_traverse_test',
        'ui.pages.charger_test.iterm_test',
        'ui.pages.charger_test.regulation_voltage_ui',
        'ui.pages.charger_test.status_register_test',
        'ui.pages.consumption_test',
        'ui.pages.consumption_test.consumption_test',
        'ui.pages.consumption_test.consumption_test_wrapper',
        'ui.pages.consumption_test.high_low_temp_test_ui',
        'Bes_I2CIO_Interface',
        'i2c_interface_x64',
        'i2c_demo_x64',
        'efuse_script_caller',
        'lib.i2c.Bes_I2CIO_Interface',
        'lib.i2c.i2c_interface_x64',
        'lib.i2c.i2c_demo_x64',
        'lib.i2c.efuse_script_caller',
        'lib.download_tools.download_script',
    ],
    hookspath=[os.path.join(PROJECT_ROOT, 'hooks')],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pyqtgraph.opengl',
        'OpenGL',
        'importlib_resources',
        'serial.tools.list_ports_osx',
        'numpy.array_api',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='KK_Lab',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(PROJECT_ROOT, 'resources', 'icons', 'kk_lab.ico'),
)