CHIP_CONFIG = {
    "chip_name": "bes1502p_watch",
    "main_die": "BES1502P",
    "main_die_iic_weight": "",
    "main_die_iic_device_addr": "",
    "pmu": "PMU1502P",
    "pmu_iic_weight": "",
    "pmu_iic_device_addr": "",
    "flash1": "",
    "flash2": "",
    "flash3": "",
    "psram1": "",
    "psram2": "",
    "apsram1": "",
    "apsram2": "",
    "power_distribution": {},
}
