CHIP_CONFIG = {
    "chip_name": "bes2002",
    "main_die": "BES2002",
    "main_die_i2c_width": "",
    "main_die_i2c_addr": "",
    "pmu": "PMU2002",
    "pmu_i2c_width": "",
    "pmu_i2c_addr": "",
    "flash1": "",
    "flash2": "",
    "flash3": "",
    "psram1": "",
    "psram2": "",
    "apsram1": "",
    "apsram2": "",
    "power_distribution": {},
}
