CHIP_CONFIG = {
    "chip_name": "bes3601p",
    "main_die": "BES3601P",
    "main_die_version": "",
    "main_die_i2c_width": "",
    "main_die_i2c_addr": "",
    "main_die_pmu": "",
    "main_die_pmu_version": "",
    "main_die_pmu_i2c_width": "",
    "main_die_pmu_i2c_addr": "",
    "has_pmu": "",
    "pmu": "PMU3601P",
    "pmu_version": "",
    "pmu_i2c_width": "",
    "pmu_i2c_addr": "",
    "flash1": "",
    "flash2": "",
    "flash3": "",
    "psram1": "",
    "psram2": "",
    "apsram1": "",
    "apsram2": "",
    "power_distribution": {},
}
