CHIP_CONFIG = {
    "chip_name": "pmu_1813",
    "main_die": "",
    "main_die_version": "",
    "main_die_i2c_width": "",
    "main_die_i2c_addr": "",
    "main_die_pmu": "",
    "main_die_pmu_version": "",
    "main_die_pmu_i2c_width": "",
    "main_die_pmu_i2c_addr": "",
    "has_pmu": "",
    "pmu": "PMU1813",
    "pmu_version": "",
    "pmu_i2c_width": "",
    "pmu_i2c_addr": "0x17",
    "flash1": "",
    "flash2": "",
    "flash3": "",
    "psram1": "",
    "psram2": "",
    "apsram1": "",
    "apsram2": "",
    "power_distribution": {},
}
